# typed: false
# frozen_string_literal: true

# Homebrew formula for preso CLI
# This file is auto-generated by the release workflow
# Manual edits will be overwritten

class Preso < Formula
  desc "PRESO Renders Engaging Slides On-demand - Slidev presentation CLI"
  homepage "https://github.com/funkymonkeymonk/preso"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/funkymonkeymonk/preso/releases/download/v0.0.2/preso-darwin-arm64"
      sha256 "850bd5d7ad14192cafbc6446315f28fddd82c2765a7e2cb28612d2879015c310"

      def install
        bin.install "preso-darwin-arm64" => "preso"
      end
    else
      url "https://github.com/funkymonkeymonk/preso/releases/download/v0.0.2/preso-darwin-x64"
      sha256 "120f4aa7be4b53ce2bee9cb536c302a0331b1bfb5e89098970e01594b3a76179"

      def install
        bin.install "preso-darwin-x64" => "preso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/funkymonkeymonk/preso/releases/download/v0.0.2/preso-linux-arm64"
      sha256 "9e56128445a0e9d94552c744b37fbe373a167721294a34afad924d154d48e067"

      def install
        bin.install "preso-linux-arm64" => "preso"
      end
    else
      url "https://github.com/funkymonkeymonk/preso/releases/download/v0.0.2/preso-linux-x64"
      sha256 "7a41e59da5273409485a3a19747bcc3b646982ded4e200123d708943b0860c2f"

      def install
        bin.install "preso-linux-x64" => "preso"
      end
    end
  end

  test do
    system "#{bin}/preso", "--version"
  end
end
